### ISSUE TITLE
KeySetWithPredicate fails when given Predicate is Regex

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast-go-client#106]
I have below code segment
```$go
        entrySet, err := flow.createdMap.EntrySetWithPredicate(core.Regex("this", valueRegex))
	...
	actualValues, err := flow.createdMap.ValuesWithPredicate(core.Regex("this", valueRegex))
	...
        keySet, err := flow.createdMap.KeySetWithPredicate(core.Regex("this", keyRegex))
       ...
```
It works for `EntrySetWithPredicate`, `ValuesWithPredicate`. However, `KeySetWithPredicate` returns empty `keySet`

**Comment by lazerion** [comment]
Hi @furkansenharputlu 
```
mp.Put(keyGen.Generate(42),keyGen.Generate(42))
```
you use same regex for both value and key, when I change test case applying value regex on `KeySetWithPredicate` it worked, does `KeySetWithPredicate` with `value regex`?

**Comment by furkansenharputlu** [comment]
@lazerion Yes, it is. It should be ```value regex```. It searches values according to predicate then turns those values' keys. Hence, this issue is resolved.

**Comment by lazerion** [comment]
@furkansenharputlu thanks closing.
