### ISSUE TITLE
Hazelcast Client Engine does not know Go client

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast-go-client#142]
Go client authenticate itself as "GO" but this type is not defined on hazelcast side.

`com.hazelcast.core.ClientType` Enum should have  `GO` as new value.

`com.hazelcast.nio.ConnectionType` Enum have a `GO_CLIENT` similar to other client types. 

There are some methods makes some conversions like `com.hazelcast.client.impl.protocol.task.AuthenticationBaseMessageTask#setConnectionType()`, these should have a go improvement.

**Comment by mustafaiman** [comment]
The same changes has been made for node.js client recently. You can take a look at this PR: https://github.com/hazelcast/hazelcast/pull/8556/files
