### ISSUE TITLE
Confusing Error message : Connecting to cluster with wrong group name.

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-go-client#215]
## Scenario

From the GO Client connect to a hazelcast cluster that has a different group-name than the one configured in the client config on the GO client.

The error message return should inform the user to change their client config group name, instead it complains about invalid credentials which is misleading the the user...

```
2018/04/09 12:27:55 New State :  STARTING
2018/04/09 12:27:55 the following error occured while trying to connect to cluster:  invalid credentials!
```

There is also a typo "occured" should be "occurred"

**Comment by SaitTalhaNisanci** [comment]
@dbrimley I dont think we have the separation between `wrong group name` and `wrong group password`. Both of them are combined under `invalid credentials`. If we want to separate them we should do it in Java first.

**Comment by SaitTalhaNisanci** [comment]
We can reopen this if the server side separates those two cases.
