### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by djchapm** [hazelcast/hazelcast-go-client#297]
Go version: go version go1.10.1 darwin/amd64
Hazelcast Go Client version: master
Hazelcast server version: 3.10
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version : OSX

#### Expected behaviour
Tests Run fine when running $ sh localTest.sh

#### Actual behaviour
gometalinter ./...  detected problems
sample/serialization/portable/portable_example.go:1::warning: file is not gofmted with -s (gofmt)
sample/serialization/portable/portable_example.go:1::warning: file is not goimported (goimports)

#### Steps to reproduce the behaviour
get latest... go to hazelcast-go-client dir and run sh localTest.sh.

I tried doing gofmt -s -w and goimports -w but I'm really new at Golang so not sure of the issue.  Seeing if it runs fine for anyone else.

**Comment by SaitTalhaNisanci** [comment]
Hello,

Did you modify that example or do you get this error even when your directory is exactly the same as the current master?

Can you make sure you dont have any files modified and try `sh linter.sh` in `hazelcast-go-client` dir?

**Comment by djchapm** [comment]
No... here just did a fresh pull again from master and ran build.sh:
**X7022495:hazelcast-go-client DJCHAPM$ git pull**
...Fast-forward
 core/errors.go            | 12 ++++++++++++
 internal/client.go        |  6 +-----
 internal/proxy_manager.go |  5 ++++-
 test/client_test.go       | 20 ++++++++++++++++++++
 4 files changed, 37 insertions(+), 6 deletions(-)

**X7022495:hazelcast-go-client DJCHAPM$ sh build.sh** 
~/Projects/go/src/github.com/hazelcast/hazelcast-go-client ~/Projects/hazelcast/hazelcast-go-client
gometalinter ./...  detected problems
sample/serialization/portable/portable_example.go:1::warning: file is not gofmted with -s (gofmt)
sample/serialization/portable/portable_example.go:1::warning: file is not goimported (goimports)

**And here's output from linter.sh - I removed all the warnings as there are many... here are the errors printed:**
core/aggregator/aggregators.go:30:2:error: use of internal package not allowed (vet)
core/predicate/predicates.go:19:2:error: use of internal package not allowed (vet)
core/projection/projection.go:17:8:error: use of internal package not allowed (vet)
hazelcast.go:21:2:error: use of internal package not allowed (vet)
internal/aggregation/aggregator_impl.go:18:2:error: use of internal package not allowed (vet)
internal/client.go:23:2:error: cannot find package "github.com/hazelcast/hazelcast-go-client/config/property" in any of: (vet)
internal/client.go:25:2:error: cannot find package "github.com/hazelcast/hazelcast-go-client/internal/discovery" in any of: (vet)
internal/client.go:26:2:error: use of internal package not allowed (vet)
internal/client.go:27:2:error: use of internal package not allowed (vet)
internal/cluster.go:26:2:error: use of internal package not allowed (vet)
internal/cluster.go:27:2:error: use of internal package not allowed (vet)
internal/colutil/util.go:19:2:error: use of internal package not allowed (vet)
internal/colutil/util.go:20:2:error: use of internal package not allowed (vet)
internal/colutil/util.go:21:2:error: use of internal package not allowed (vet)
internal/discovery/hazelcast_cloud_discovery.go:29:2:error: use of internal package not allowed (vet)
internal/discovery/hazelcast_cloud_discovery.go:30:2:error: use of internal package not allowed (vet)
internal/flake_id_generator.go:18:2:error: use of internal package not allowed (vet)
internal/map.go:24:2:error: use of internal package not allowed (vet)
internal/partition.go:22:2:error: use of internal package not allowed (vet)
internal/projection/projections_impl.go:18:2:error: use of internal package not allowed (vet)
internal/proxy.go:22:2:error: use of internal package not allowed (vet)
internal/serialization/data.go:21:2:error: use of internal package not allowed (vet)
internal/serialization/default_portable_reader.go:21:2:error: use of internal package not allowed (vet)
internal/serialization/default_portable_reader.go:22:2:error: use of internal package not allowed (vet)
internal/serialization/object_data.go:23:2:error: use of internal package not allowed (vet)
internal/serialization/serialization.go:24:2:error: use of internal package not allowed (vet)
internal/serialization/serialization.go:25:2:error: use of internal package not allowed (vet)
internal/serialization/serialization.go:26:2:error: use of internal package not allowed (vet)
sample/map/projection/projection_example.go:22:2:error: use of internal package not allowed (vet)
serialization/classdef/class_definition_builder.go:8:2:error: use of internal package not allowed (vet)

**Comment by yuce** [comment]
Closing this issue, since it's not related to the latest codebase anymore.
