### ISSUE TITLE
Near Cache

### ISSUE THREAD

**Issue by SaitTalhaNisanci** [hazelcast/hazelcast-go-client#408]
- [ ] Implement Basic Near Cache
- [ ] Implement Preloader
- [ ] Implement Near Cache Statistics 
- [ ] Implement Eventual Consistency

**Comment by rakeshrvce** [comment]
Is this feature coming in any release?

**Comment by yuce** [comment]
Near Cache is implemented in Go Client v1.3.0, so closing this issue.
