### ISSUE TITLE
Make client work when addresses configured via different interface than members

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-go-client#438]
Clients and members were forced to configure the same interface when adding a member address to config.

https://github.com/hazelcast/hazelcast/pull/14104
With this prd on the java side, we have relaxed the rules. As long as hostnames are resolved to the same IP when DNS lookup made on the client side following setups are allowed.

1. Member hostname <-> client different hostname
2. Member ip       <-> client different hostname
3. Member hostname <-> client ip

Same needs to be applied to go client

**Comment by yuce** [comment]
This is supposed to work with Go Client v1, closing.
