### ISSUE TITLE
Compile issues during `go get`

### ISSUE THREAD

**Issue by philippgille** [hazelcast/hazelcast-go-client#439]
Go version: `go version go1.10.1 windows/amd64`
Hazelcast Go Client version: Latest commit: `0df91da3f327f8df8e0b05ead439a271484f7407`
Hazelcast server version: /
Number of the clients: /
Cluster size, i.e. the number of Hazelcast cluster members: /
OS version : Windows 10 Pro 1803

#### Expected behaviour

Successfull download and compile of the `hazelcast-go-client` package

#### Actual behaviour

The download seems to be successful, but during the compile step I get the following error:

```
# github.com/hazelcast/hazelcast-go-client/internal
..\..\hazelcast\hazelcast-go-client\internal\statistics.go:154:12: undefined: syscall.Rlimit
..\..\hazelcast\hazelcast-go-client\internal\statistics.go:155:12: undefined: syscall.Getrlimit
..\..\hazelcast\hazelcast-go-client\internal\statistics.go:155:30: undefined: syscall.RLIMIT_NOFILE
```

#### Steps to reproduce the behaviour

`go get -u "github.com/hazelcast/hazelcast-go-client"`

I also tried just downloading the package first, then cd into the package directory and then compile, but that should be the same so it also leads to the same error:
1. `go get -d "github.com/hazelcast/hazelcast-go-client"`
2. `cd $(go env GOPATH)/src/github.com/hazelcast/hazelcast-go-client`
3. `go build`

**Comment by philippgille** [comment]
I updated my Go version to 1.11.5, but that didn't fix this.

**Comment by SaitTalhaNisanci** [comment]
Hi @philippgille, with #448 this should be fixed.
