### ISSUE TITLE
Client reports version as 0.5-SNAPSHOT

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-go-client#465]
Go version: 1.12.5
Hazelcast Go Client version: "0.5" ?
Hazelcast server version: 3.12
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version : OSX 10.14.5

#### Expected behaviour
Reports as "0.5"

#### Actual behaviour
Reports as "0.5-SNAPSHOT"

#### Steps to reproduce the behaviour
Download current, connect to server, a message will appear server side and client side reporting the version

```
 INFO: hz.client_1 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is SHUTDOWN
```

**Comment by sancar** [comment]
@neilstevenson 
When you call `go get ` it will fetch the latest master. In our repo, the latest master is always SNAPSHOT. 
To get a specific release, you need to fetch that tag via git specifically. So it is expected get snapshot when you do `go get`. 

To get `0.5` when you do `go get`, the master should point to the latest stable release and we should have a different `dev` branch. We are not applying this approach at the moment
