### ISSUE TITLE
Question: Different than redis?

### ISSUE THREAD

**Issue by asad-awadia** [hazelcast/hazelcast-go-client#472]
How is using hazelcast for distributed data structures like a map different than having a centralised redis? Is it just the resiliency? i.e. if one client fails then the data still survives?

How is the data moving around? multicast and in memory?

**Comment by burakcelebi** [comment]
Hi @asad-awadia, it is a lot different.

**Comment by burakcelebi** [comment]
Hi @asad-awadia! Thank you for your question. Scalability and availability are two strengths of Hazelcast. I believe this section is a nice introduction: https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#hazelcast-overview

I'll keep open this issue for a while. Please let us know if you have further questions or comments. I'm happy to help :)
