### ISSUE TITLE
no semantic versioning on tags

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/hazelcast-go-client#476]
Go version: 1.13
Hazelcast Go Client version: master
OS version: OSX

Tagging versions must be semantic versioning(eg: v0.5.0). Otherwise, go modules can't resolve v0.5 or v0.4 tagged versions.

More details at https://blog.golang.org/publishing-go-modules

#### Expected behaviour
go modules(go.mod) should resolve hazelcast-go-client with its version.

#### Actual behaviour
go modules(go.mod) resolves only on master branch.

#### Steps to reproduce the behaviour
try to add `github.com/hazelcast/hazelcast-go-client v0.5`

go.mod example: 
```
module mymodule

go 1.13

require (
  github.com/hazelcast/hazelcast-go-client v0.5
)
```

**Comment by gulcesirvanci** [comment]
Hi @ilkerkorkut , thank you for your issue. I added tag `v0.5.0`. It will solve this problem.
