### ISSUE TITLE
Failed to connect to the Hazelcast cluster v4.0

### ISSUE THREAD

**Issue by JorgenPo** [hazelcast/hazelcast-go-client#479]
Go version: 1.14
Hazelcast Go Client version: 0.6.0
Hazelcast server version: 4.0
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version : Manjaro Linux

I am trying to run the following code: 
```go
func main() {
	config := hazelcast.NewConfig()
	client, err := hazelcast.NewClientWithConfig(config)

	if err != nil {
		log.Fatalf("Failed to create hazelcast client: %v", err)
	}

	log.Printf("Client name is %s", client.Name())
}
```

#### Expected behaviour
The client connects to the cluster and the name is printed. 

#### Actual behaviour
Client is created with an error.

Client logs:
```
2020/03/16 17:26:00 github.com/hazelcast/hazelcast-go-client/internal.(*lifecycleService).fireLifecycleEvent
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is STARTING
2020/03/16 17:26:00 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] Trying to connect to 127.0.0.1:5701 as owner member.
2020/03/16 17:26:00 github.com/hazelcast/hazelcast-go-client/internal.(*Connection).close
WARN: hz.client_1 [dev] [0.5-SNAPSHOT] Connection : %!v(PANIC=String method: interface conversion: interface is nil, not core.Address)  closed, err:  read tcp 127.0.0.1:44900->127.0.0.1:5701: read: connection reset by peer
```

Server logs:
```
Mar 16, 2020 5:26:00 PM com.hazelcast.internal.nio.tcp.TcpIpConnection
WARNING: [172.18.241.63]:5701 [dev] [4.0] Connection[id=2, /127.0.0.1:5701->/127.0.0.1:44900, qualifier=null, endpoint=null, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=2, /127.0.0.1:5701->/127.0.0.1:44900, qualifier=null, endpoint=null, alive=true, connectionType=NONE], thread=hz.upbeat_hodgkin.IO.thread-in-1
java.lang.IllegalStateException: Unknown protocol: CB2
	at com.hazelcast.internal.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:116)
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:137)
	at com.hazelcast.internal.networking.nio.NioPipeline.lambda$start$0(NioPipeline.java:127)
	at com.hazelcast.internal.networking.nio.NioThread.processTaskQueue(NioThread.java:354)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:289)
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248)
```

By the way, I am using go client v 0.6.0, but there is [0.5-SNAPSHOT] in the client log.

#### Steps to reproduce the behaviour
Run the code

**Comment by burakcelebi** [comment]
Hi @JorgenPo, for now, you cannot connect to a 4.0 cluster with a Go client. Currently, we are working on version 4.0 of Go Client. 

You can download Hazelcast IMDG 3.12.x to connect from the Go client you use.

Please see our compatibility matrix: https://hazelcast.org/imdg/clients-languages/#client-compatibility

I'll keep this issue open for a while. Please let me know your experience with the client :)

Cheers.

**Comment by JorgenPo** [comment]
Thanks @burakcelebi for a response. The client works with Hazelcast 3.12 perfectly. Thank you again!

**Comment by burakcelebi** [comment]
Great! Please keep us posted to share your experience and requests :) Please also see other useful channels below:

- http://stackoverflow.com/questions/tagged/hazelcast
- https://gitter.im/hazelcast/hazelcast
- https://groups.google.com/forum/#!forum/hazelcast

**Comment by martinreus-form3** [comment]
Can we reopen this? It seems I am having the same issue when running hazelcast in a cluster formation using the official helm charts in minikube. Helm release is as follows:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hazelcast
spec:
  wait: true
  chart:
    git: https://github.com/hazelcast/charts
    ref: master
    path: stable/hazelcast
  releaseName: hazelcast
  values:
    service:
      name: hazelcast
    mancenter:
      enabled: false
```

The go code is as simple as 
```
	config := hazelcast.NewConfig()
	networkConfig := config.NetworkConfig()
	networkConfig.AddAddress("hazelcast:5701")
	client, _ := hazelcast.NewClientWithConfig(config)
	hmap, _ := client.GetMap("fps-klist-store")
```

but this yields the same error described in the beginning question. Is this still a problem with the client or some misconfiguration on my side?

**Comment by burakcelebi** [comment]
Hi @martinreus-form3, unfortuntely, you cannot connect to a 4.0 cluster with a Go client at the moment. As of now, we do not have a v4.0 of Go Client.

You can download Hazelcast IMDG 3.12.x to connect from the Go client you use.

Please see our compatibility matrix: https://hazelcast.org/imdg/clients-languages/#client-compatibility

**Comment by yuce** [comment]
For anyone bumping to this issue: Go client v1 supports Hazelcast v4 and v5 clusters. You can check out the latest release information here: https://github.com/hazelcast/hazelcast-go-client/releases
