### ISSUE TITLE
Explicitly registering Portable ClassDefinitions fails with multiple PortableFactories and overlapping classIds [API-1258]

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-go-client#480]
see following issue description 
https://github.com/hazelcast/hazelcast/issues/16820

Java fix
https://github.com/hazelcast/hazelcast/pull/16832

**Comment by yuce** [comment]
Works correctly for the Go client, checked by: https://github.com/hazelcast/hazelcast-go-client/pull/758
