### ISSUE TITLE
Client becomes unresponsive and has stuck go routines when cluster members are added

### ISSUE THREAD

**Issue by codingnj10** [hazelcast/hazelcast-go-client#483]
Go version: 1.12
Hazelcast Go Client version: 0.6.0
Hazelcast server version: 3.11.7
Number of the clients: 1
Cluster size: 1-10 
OS version : OSX

#### Expected behaviour
We have 5 cluster members and sometimes we scale them down to 1 and up to 10.  If we add or remove too many at a time, the client becomes unresponsive and doing a `pprof` shows stuck go routines. (I attached the pprof data)

#### Actual behaviour
Scaling members shouldn't cause the client to become unresponsive and having stuck go routines.

#### Steps to reproduce the behaviour
1. Start a cluster with 5 members. 
2. Connect client to the cluster. 
3. Remove 4 members, (it will work fine). 
4. Add 4 or more members.
5. After the 3rd one is added, next additions won't be registered or logged and the client will become unresponsive when running operations like `poll()` or `put()`
[hazelcast_pprof.txt](https://github.com/hazelcast/hazelcast-go-client/files/4490042/hazelcast_pprof.txt)  
  
Might be related to this. https://github.com/hazelcast/hazelcast-go-client/issues/463

**Comment by burakcelebi** [comment]
Hi @codingnj10, thank you for submitting this. We are on it. cc: @gulcesirvanci, @asimarslan

**Comment by gulcesirvanci** [comment]
Hi @codingnj10 , Do you have a reproduce unit test?

**Comment by codingnj10** [comment]
Sorry, I do not.

**Comment by yuce** [comment]
Go client was refactored after this issue was created. Please try with the latest Go client and reopen the issue if the problem persists.
