### ISSUE TITLE
Paging Predicate

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-go-client#484]
Currently, the Go client does not support Hazelcast's [paging predicates](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#filtering-with-paging-predicates).

**Comment by jewertow** [comment]
I want to work on this issue. Could you assign me?

**Comment by jewertow** [comment]
@burakcelebi ping ;)

**Comment by burakcelebi** [comment]
Hey @jewertow! Apologies, how I did miss this :) It's yours now. Please let me know if you have any questions.

**Comment by jewertow** [comment]
@burakcelebi I started working on this issue, but I have a lot of problems with deserialization a request with paging predicate on the server side. Is there a documentation with protocol description?

**Comment by yuce** [comment]
No new predicates will be added to the Go client, so closing.
