### ISSUE TITLE
Partition predicate

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast-go-client#485]
Currently, the Go client does not support Hazelcast's [partition predicate](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#filtering-with-partition-predicate).

**Comment by buraksezer** [comment]
Hi team,

I would like to take this issue.

**Comment by burakcelebi** [comment]
Great @buraksezer! It's yours :)

**Comment by yuce** [comment]
No new predicates will be added to the Go client, so closing.
