### ISSUE TITLE
No available connection to working cluster member

### ISSUE THREAD

**Issue by toljio** [hazelcast/hazelcast-go-client#486]
Go version: 1.14.1
Hazelcast Go Client version: latest (0.5-SNAPSHOT)
Hazelcast server version: 3.12.6
Number of the clients: 1
Cluster size: 2
OS version : Linux and OSX

#### Expected behavior
Go client works at same speed as Java client with Hazelcast cluster.

#### Actual behavior
Cluster access delay (1s). I think it is InvocationRetryPause. But why does it occur?
Java client do the same operations at that cluster without this behavior.

#### Steps to reproduce the behavior
1. Create Hazelcast cluster with 2 nodes
2. Configure Go client - add addresses of cluster:
`clientConfig.NetworkConfig().AddAddress("127.0.0.1:5701", "127.0.0.1:5702")`
3. Add TraceLevel
`config.SetProperty(property.LoggingLevel.Name(), logger.TraceLevel)`
4. Run example _sample/helloworld/two/two.go_
5. Get the expected result, but with delay 1s...
6. Fetch log messages:
`2020/04/25 17:20:26 github.com/hazelcast/hazelcast-go-client/internal.(*invocationServiceImpl).sendToAddress
TRACE: hz.client_1 [dev] [0.5-SNAPSHOT] Sending invocation to  127.0.0.1:5702  failed, err:  No available connection to address 127.0.0.1:5702
2020/04/25 17:20:26 github.com/hazelcast/hazelcast-go-client/internal.(*invocationServiceImpl).logError
TRACE: hz.client_1 [dev] [0.5-SNAPSHOT] Invocation with correlation id:  4  got an error:  No available connection to address 127.0.0.1:5702
`
7. Server log:
`INFO: [127.0.0.1]:5702 [dev] [3.12.6] Connection[id=48, /127.0.0.1:5702->/127.0.0.1:50981, qualifier=null, endpoint=[127.0.0.1]:50981, alive=false, type=GO_CLIENT] closed. Reason: Connection closed by the other side`

**Comment by yuce** [comment]
Go client was refactored after this issue was created. Please re-open the issue if the problem persists.
