### ISSUE TITLE
Extension: Secure random for UUID

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-go-client#488]
IMDG's UUID utility (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/UuidUtil.java) allows for the use of ordinary random and secure random

Go's version (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/UuidUtil.java#L94) does not

It seems secure random packages exist - https://godoc.org/github.com/theckman/go-securerandom

**Comment by yuce** [comment]
@neilstevenson We use `rand.Reader` with Go client v1 which is cryptographically secure according to its documentation. Closing this issue: https://github.com/hazelcast/hazelcast-go-client/blob/4a08c82a67941c8fe4a8c83b620141b870d64a36/types/uuid.go#L35
