### ISSUE TITLE
Endian format on Murmur3

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-go-client#489]
Current GO client is using *LITTLE_ENDIAN* format,
https://github.com/hazelcast/hazelcast-go-client/blob/master/internal/util/murmur/murmur.go#L35

Default configuration for IMDG is *BIG_ENDIAN*,
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java#L48

**Comment by neilstevenson** [comment]
See also https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/HashUtil.java#L98

Only a comment, but suggests *LITTLE_ENDIAN*

**Comment by yuce** [comment]
@neilstevenson Closing this issue since other clients also use little endian.
