### ISSUE TITLE
Confusing chapter about Cloud Discovery

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast-go-client#490]
Original report: https://github.com/hazelcast/hazelcast-python-client/issues/207

I looked at the README, the problem described in the issue above also exists in this client. 

Also, we need to update the code samples since they use default system certificates. However, Hazelcast Cloud uses private certificate pair now. See https://github.com/hazelcast/hazelcast-go-client/blob/master/sample/hzclouddiscovery/cloud_discovery_example.go#L29

**Comment by yuce** [comment]
@mdumandag The doc for Hz Cloud is at: https://github.com/hazelcast/hazelcast-go-client/blob/41af578381ebb6d64339c3f498e848551ba6160d/doc.go#L20 and code sample is at: https://github.com/hazelcast/hazelcast-go-client/blob/master/examples/discovery/cloud/main.go Closing this issue now, but feel free to re-open it if necessary.
