### ISSUE TITLE
Client 0.6.0 reports itself as 0.5-SNAPSHOT

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-go-client#493]
This is why https://github.com/hazelcast/hazelcast-go-client/blob/master/internal/connection_manager.go#L35

Gives
```
INFO: hz.client_1 [dev] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is STARTING
```

**Comment by yuce** [comment]
Thanks @neilstevenson. Closing this ticket since the client has a different version now.
