### ISSUE TITLE
EntryAdded listener method invoked three times 

### ISSUE THREAD

**Issue by JorgenPo** [hazelcast/hazelcast-go-client#495]
Go version: 1.15.3
Hazelcast Go Client version: 0.6.0
Hazelcast server version: 3.12
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 3
OS version : Linux  

I set up an entry listener with predicate using _AddEntryListenerWithPredicate_ method. After that I put one new entry into the hazelcast map. 

Note: When I use _AddEntryListener_ (without a predicate) everything works fine.

#### Expected behaviour
EntryAdded listener method invoked only once. With the new map entry I've put. 
 
#### Actual behaviour
EntryAdded listener method invoked three times (probably equals cluster size). 

#### Steps to reproduce the behaviour
1. Set entry listener with predicate using _AddEntryListenerWithPredicate_ method.
2. Put an entry to the map

Maybe I do something wrong. I am ready to give more infomation to invistigate the reason of problem.

**Comment by JorgenPo** [comment]
I've uploaded a test program source to reproduce the problem and the output of its execution.

https://gist.github.com/JorgenPo/719332b853f1cb1e02a6bb74fd26f992

**Comment by yuce** [comment]
Fixed in v1 preview 1.
