### ISSUE TITLE
Enhancement, make Go client version visible

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-go-client#498]
See https://github.com/hazelcast/hazelcast-cpp-client/issues/612, the client version is available for C++, so why not for GoLang also

The version is internal, in https://github.com/hazelcast/hazelcast-go-client/blob/master/internal/connection_manager.go#L35

**Comment by yuce** [comment]
@neilstevenson This feature was implemented at v1.1.0
