### ISSUE TITLE
[TRACKING ISSUE] add test for ClientNonStopNearCache scenario

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#502]
The tracking issue for the Java side PR.

**add test for ClientNonStopNearCache scenario**

See https://github.com/hazelcast/hazelcast/pull/16717 for details.

---

**Comment by yuce** [comment]
@enozcan Could you consider this issue when implementing the near cache?

**Comment by yuce** [comment]
There is no near cache for the Go client, closing.

**Comment by willthrom** [comment]
I am confuse with this last statement. 

https://hazelcast.com/clients/go/#client-features
**Recently Released Go Features**
Near Cache: An implementation of [Hazelcast’s near cache functionality](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#near-cache) for the GoLang client.

But I cannot find where is it or how to use it..

**Comment by yuce** [comment]
Hi @willthrom, thanks for your comment. Go client never had the near cache and it doesn't have it now. The information on that page is not correct, we will fix that.
