### ISSUE TITLE
[TRACKING ISSUE] Fix class definitions registration with same class id [API-1260]

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#505]
The tracking issue for the Java side PR.

**Fix class definitions registration with same class id**

See https://github.com/hazelcast/hazelcast/pull/16831 for details.

---

When class definition is registered explicitly from serialization config
, if user gives same class id in different factories, we could not
handle it correctly. This pr makes sure it works from now on.

fixes https://github.com/hazelcast/hazelcast/issues/16820

(cherry picked from commit 29b1fb3ad3f29e78757d472ab827bb0b222b39ad)

**Comment by srknzl** [comment]
fyi this is duplicate of https://github.com/hazelcast/hazelcast-go-client/issues/480

**Comment by yuce** [comment]
Thanks @srknzl !

**Comment by yuce** [comment]
Check whether a test exists for this.

**Comment by yuce** [comment]
Closing, duplicate of https://github.com/hazelcast/hazelcast-go-client/issues/480
