### ISSUE TITLE
[TRACKING ISSUE] Shutdown executor in finally

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#506]
The tracking issue for the Java side PR.

**Shutdown executor in finally**

See https://github.com/hazelcast/hazelcast/pull/16878 for details.

---

closes https://github.com/hazelcast/hazelcast/issues/16397

In logs, we can see that sometimes `awaitTermination` doesn't finish threads properly in the given time window, to close executor for those cases, this PR adds shutdownNow in the finally block. This will help to pinpoint the real failure, if there is any, for the future failures.

**Comment by yuce** [comment]
Not relevant to Go client, closing.
