### ISSUE TITLE
[TRACKING ISSUE] Get rid of ResponseParameters for single response

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#511]
The tracking issue for the Java side PR.

**Get rid of ResponseParameters for single response**

See https://github.com/hazelcast/hazelcast/pull/17162 for details.

---

ClientCodec returns the parameters on a different object.
This is necessary for a multivariable response but for single
types it is an unnecessary object.

The same applied to single variable requests

Protocol pr: https://github.com/hazelcast/hazelcast-client-protocol/pull/328

**Comment by yuce** [comment]
- Does not exist in the Go client
