### ISSUE TITLE
Change import paths to hazelcast.org

### ISSUE THREAD

**Issue by mustafaiman** [hazelcast/hazelcast-go-client#52]
Import paths start with `github.com/hazelcast` right know. We decided that import paths should start with `hazelcast.org` instead. This may include also a keyword like `goclient` at the end of the address: `hazelcast.org/goclient`.

Since version control is deeply involved with package hierarchy in golang, we may have to define some redirections in `hazelcast.org` website.

**Comment by furkansenharputlu** [comment]
@mustafaiman People are going to install Go client with
 ```go get https://github.com/hazelcast/hazelcast-go-client``` command. [Here](https://golang.org/doc/code.html#ImportPaths)  It says that "If you keep your code in a source repository somewhere, then you should use the root of that source repository as your base path. For instance, if you have a GitHub account at github.com/user, that should be your base path."

**Comment by mustafaiman** [comment]
according to go community conventions and golang documentations, using `github.com` in import paths is advised. Popular packages does the same. I am closing this issue.
