### ISSUE TITLE
[TRACKING ISSUE] Add getAndDecrement method to IAtomicLong

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#525]
The tracking issue for the Java side PR.

**Add getAndDecrement method to IAtomicLong**

See https://github.com/hazelcast/hazelcast/pull/17699 for details.

---

There were getAndDoX and doXAndGet method pairs for the IAtomicLong
but there were just the decrementAndGet, getAndDecrement was missing.
One may do getAndAdd(-1) to get the desired behaviour, so there were
no missing functionality but the getAndDecrement method is added to
make the API more consistent.

Also, updated the codecs and message tasks of the LongRegister with
the recent changes.

**Comment by yuce** [comment]
- No AtomicLong
