### ISSUE TITLE
[TRACKING ISSUE] Release acquired sessions on failure for SessionAwareSemaphore

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast-go-client#530]
The tracking issue for the Java side PR.

**Release acquired sessions on failure for SessionAwareSemaphore**

See https://github.com/hazelcast/hazelcast/pull/17826 for details.

---

In case of an unspecified exception, `acquire`, `tryAcquire` and
`drainPermits` methods were not releasing the acquired permits.
This is an attempt to fix that problem by catching unspecified errors,
releasing the number of acquired permits, and rethrowing.

I will prepare backports once this PR is approved and merged.

**Comment by yuce** [comment]
- no CP
