### ISSUE TITLE
Unable to connect to a free hazelcast cloud cluster using discovery token 

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast-go-client#538]
Go version:  go1.15.8 linux/amd64
Hazelcast Go Client version: v0.6.0
Hazelcast server version: 4.0.2
Number of the clients: 1
Cluster size, i.e. the number of Hazelcast cluster members: 1
OS version : Linux

#### Expected behaviour

Hi, I tried to connect to a free cluster that I created at https://cloud.hazelcast.com, but I could not.

I have a cluster name and a cloud discovery token that I got from "Configure Clients" section in the cluster view. 

 I expected to be able to connect to it using my cluster name and token according to this part the README. https://github.com/hazelcast/hazelcast-go-client#58-enabling-hazelcast-cloud-discovery

**Note**: I can connect to the cluster with cluster name and discovery token using other hazelcast clients that I tried: python and node.js 

#### Actual behaviour

Go client tries to connect but get a connection reset error. 

Error produced:
```

2021/02/06 13:43:31 github.com/hazelcast/hazelcast-go-client/internal.(*lifecycleService).fireLifecycleEvent
INFO: hz.client_1 [test] [0.5-SNAPSHOT] HazelcastClient 0.5-SNAPSHOT is STARTING
2021/02/06 13:43:33 github.com/hazelcast/hazelcast-go-client/internal.(*clusterService).connectToAddress
INFO: hz.client_1 [test] [0.5-SNAPSHOT] Trying to connect to 100.120.109.85:31942 as owner member.
2021/02/06 13:43:34 github.com/hazelcast/hazelcast-go-client/internal.(*Connection).close
WARN: hz.client_1 [test] [0.5-SNAPSHOT] Connection : %!v(PANIC=String method: interface conversion: interface is nil, not core.Address)  closed, err:  read tcp 192.168.1.113:44570->3.9.172.129:31942: read: connection reset by peer

```

#### Steps to reproduce the behaviour
1. Create a free tier hazelcast cloud cluster
2. Wait for it to be running
3. Get cluster name and discovery token at `Configure Clients` section
4. Use this code to run a client 
```go
package main

import (
	"fmt"
	"github.com/hazelcast/hazelcast-go-client"
)

func main() {
	config := hazelcast.NewConfig()

	config.GroupConfig().SetName("<Cluster name shown on hazelcast cloud website>")

	cloudConfig := config.NetworkConfig().CloudConfig()
	cloudConfig.SetDiscoveryToken("<Disc token shown on hazelcast cloud website>")
	cloudConfig.SetEnabled(true)

	//config.NetworkConfig().SetCloudConfig(cloudConfig)

	client , _ := hazelcast.NewClientWithConfig(config)


	mp, _ := client.GetMap("myDistributedMap")
	_, _ = mp.Put("key", "value")
	value, _ := mp.Get("key")
	fmt.Println(value)
}

```

**Comment by yuce** [comment]
@srknzl Closing this ticket since Hz Cloud support works OK with v1.0.0 Preview 4.
