### ISSUE TITLE
Client should apply the memberlist when the version greater and equal

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast-go-client#634]
Go client applies it only when the version is greater. 

We should at least investigate why it is this way on java and could it lead to a bug on go.

**Comment by yuce** [comment]
If we get the member list with same version, wouldn't it mean that we already applied that member list before? Curious about why that works differently in Java and the test that check it.

**Comment by sancar** [comment]
@yuce I don't really remember. Running a test to remember why it was the case. 
https://github.com/hazelcast/hazelcast/pull/19521
Hopefully, a test will fail. Then I will document the related code in detail

**Comment by sancar** [comment]
@yuce We could not find the reasoning and no test failed. So we have decided to change the code to only apply the greater values on java as well as it is more intuitive. See 
https://github.com/hazelcast/hazelcast/pull/19521 
Closing this issue since there is no need to take any action in go client.
