### ISSUE TITLE
Add Ringbuffer Support

### ISSUE THREAD

**Issue by yuce** [hazelcast/hazelcast-go-client#674]

**Comment by nitram509** [comment]
I wonder, why RingBuffer support was removed, it seems to me, it was there already #187 ?
Could someone please add some comments on why it was removed, where could I start investigating, and what needs to be done?

**Comment by nitram509** [comment]
relates to #751

**Comment by yuce** [comment]
Hi @nitram509 The PR you linked is for Go Client v0.6, which works only with Hazelcast 3.x. Current v1 series work with Hazelcast 4,x and 5.x but there's no RingBuffer support yet. We don't currently have a release date for this feature.

**Comment by nitram509** [comment]
@yuce thank you for your quick response.
And may I ask, how much effort you would estimate is required for an average Go developer, to implement (or migrate) v0.6.0 RingBuffer support to the latest v1.x of HazelClient?

**Comment by yuce** [comment]
Thanks for considering to contribute to the project! It wouldn't take too long, and we will help you along the way. Do you mind joining our Community Slack channel at https://hazelcastcommunity.slack.com/channels/go-client ? I am `yuce` there.

**Comment by yuce** [comment]
You can get an invitation for our Community Slack here: https://slack.hazelcast.com/

**Comment by yuce** [comment]
Ringbuffer was contributed by @nitram509 and it is merged to master.
