### ISSUE TITLE
Nil object serialization should directly return

### ISSUE THREAD

**Issue by mehmettokgoz** [hazelcast/hazelcast-go-client#913]
Default behaviour for NULL object serialization is returning NULL directly without trying to serialize it, but Go client is trying to serialize it and returns `serialization.Data{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}` object. 

Java client: https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java#L191

Go client: https://github.com/hazelcast/hazelcast-go-client/blob/master/internal/serialization/serialization.go#L65

**Comment by yuce** [comment]
`ToData` correctly returns `nil` if some value is truly `nil`. But if an interface have a type, then both type and the pointer pointing to the value must be `nil`:
```
var ni *int = nil
fmt.Println(ni == nil)
var i interface{} = ni
fmt.Println(i == nil)
```
The following code prints `true` and `false`.

There are various checks in the client that deals with the `nil` stuff. But can you add an example if there's a problem with a public API?

**Comment by yuce** [comment]
Fixed by: https://github.com/hazelcast/hazelcast-go-client/pull/932/files
