### ISSUE TITLE
DistinctAggregator serializer must read/write 32 bit not 64 bit

### ISSUE THREAD

**Issue by mehmettokgoz** [hazelcast/hazelcast-go-client#928]
Currently DistinctAggregator's serializer reads/writes `Int64` where it should be `Int32`. See the Java side implementation: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/aggregation/impl/DistinctValuesAggregator.java#L75 

Related code: https://github.com/hazelcast/hazelcast-go-client/blob/master/aggregate/aggregate_distinct.go#L49

**Comment by yuce** [comment]
Fixed by: https://github.com/hazelcast/hazelcast-go-client/pull/932
