### ISSUE TITLE
Portable objects cannot be written with an idenified data serializable serializer

### ISSUE THREAD

**Issue by mehmettokgoz** [hazelcast/hazelcast-go-client#929]
When users want to write through raw object data output, portable writer returns `GetRawDataOutput` but it fails when `WriteObject` method is used for nested portable object. See the following snippet:

`
func (p APortable) WritePortable(writer serialization.PortableWriter) {

    out := writer.GetRawDataOutput()
    out.WriteObject(p.nestedPortable)
}
`

This code produces: `interface conversion: serialization.DataOutput is *serialization.ObjectDataOutput, not *serialization.PositionalObjectDataOutput`

The following line should change: https://github.com/hazelcast/hazelcast-go-client/blob/master/internal/serialization/default_portable_writer.go#L272

**Comment by yuce** [comment]
Fixed by https://github.com/hazelcast/hazelcast-go-client/pull/932
