### ISSUE TITLE
Configuring RingBuffer capacity/TTL?

### ISSUE THREAD

**Issue by dchukmasov** [hazelcast/hazelcast-go-client#971]
Hello!

I see from the docs that RingBuffer supports capacity/TTL but I have not found the way to configure them in go client.
Is it something not yet implemented or am I missing something?

Thanks!

**Comment by yuce** [comment]
Hi @dchukmasov, you can set the capacity/TTL in your Hazelcast configuration. We don't have an API to set it in the client-side.
Here are the docs about that: https://docs.hazelcast.com/hazelcast/5.3/data-structures/ringbuffer#configuring-ringbuffer-capacity

**Comment by dchukmasov** [comment]
Thank you @yuce ! Is client-side configuration planned or not on the roadmap at all?

**Comment by yuce** [comment]
Unfortunately this feature is not on our roadmap.
