### ISSUE TITLE
transactions

### ISSUE THREAD

**Issue by Linuxlovers** [hazelcast/hazelcast-go-client#993]
Go version:1.20
Hazelcast Go Client version:1.4.1
Hazelcast server version:5.3.7
Number of the clients:
Cluster size, i.e. the number of Hazelcast cluster members:
OS version : Windows/Linux/OSX

#### Expected behavior

What do I need to do to open a transaction using a go language client? Could you please support the transaction or add relevant examples of the transaction

#### Steps to reproduce the behavior

**Comment by yuce** [comment]
Hi @Linuxlovers,
Transactions will be deprecated in the next version of Hazelcast.
So it will never be implemented in the Go Client in its current form:
https://docs.hazelcast.com/hazelcast/5.3/transactions/creating-a-transaction-interface#hide-nav

You can join Hazelcast Community Slack in case you would like to discuss your use case or ask questions:
https://slack.hazelcast.com/
